/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.OnlineVotingSystem;
import com.toedter.calendar.JDateChooser;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import static java.time.LocalDate.now;
import java.time.Month;
import java.time.Period;
import java.time.Month;
import java.time.Period;
import java.util.Calendar;
import java.util.Date;

import java.util.*;

/**
 *
 * @author HP
 */
public class AddVoter extends javax.swing.JFrame {
    
    String Vid = "AB202106";
    public static ArrayList<String> Name = new ArrayList<String>(20); 
   public static ArrayList<String> FName = new ArrayList<String>(20);
    public static ArrayList<String> Cnic = new ArrayList<String>(20);
  public static ArrayList<String> Gender = new ArrayList<String>(20);
    public static ArrayList<String> Dob = new ArrayList<String>(20);
  public static ArrayList<String> Age = new ArrayList<String>(20);
public static ArrayList<String> Address = new ArrayList<String>(20);
  public static ArrayList<String> VoterId = new ArrayList<String>(20); 
      public static int i=0;
      
     
      
     Admin backAdmin = new Admin();
     
    /**
     * Creates new form AddVoter
     */
    public AddVoter() {
        initComponents();
        this.setResizable(false);
     jtxtName.requestFocus();
     
    }
          
            
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jtxtName = new javax.swing.JTextField();
        jtxtFName = new javax.swing.JTextField();
        jtxtCnic = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbtnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboGender = new javax.swing.JComboBox<>();
        jDCDob = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtxtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });
        jtxtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNameKeyPressed(evt);
            }
        });

        jtxtFName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtFName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtxtFNameInputMethodTextChanged(evt);
            }
        });
        jtxtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFNameActionPerformed(evt);
            }
        });
        jtxtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtFNameKeyPressed(evt);
            }
        });

        jtxtCnic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtCnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCnicActionPerformed(evt);
            }
        });
        jtxtCnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCnicKeyPressed(evt);
            }
        });

        jtxtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("* Fill the following fields.");

        jbtnAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnAdd.setText("Add");
        jbtnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.darkGray));
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jbtnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnAddKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("* without dashes (xxxxxxxxxxxxx)");

        jComboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Other" }));
        jComboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGenderActionPerformed(evt);
            }
        });

        jDCDob.setDateFormatString("yyyy-MM-dd");
        jDCDob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDCDobFocusLost(evt);
            }
        });
        jDCDob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDCDobKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCnic, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboGender, jDCDob, jtxtCnic});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jtxtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtCnic, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jDCDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboGender, jDCDob, jtxtCnic});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("          Address:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("          Date Of Birth:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("          Gender:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("          CNIC:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("          Father Name:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("          Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel7});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFNameActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
       
       if(!(jtxtName.getText().trim().equals("") || jtxtFName.getText().trim().equals("") || jtxtCnic.getText().trim().equals("") 
                 || jtxtAddress.getText().trim().equals("")))
         {
             if((jDCDob.getDate() == null)){
             JOptionPane.showMessageDialog(null, "Select Date of Birth." , "Error", JOptionPane.PLAIN_MESSAGE);
             this.setVisible(true);
             }
             else{
                int cniclength = jtxtCnic.getText().length(); 
             if(cniclength<=12)
             {
             JOptionPane.showMessageDialog(null, "Cnic should have 13 digits." , "Error", JOptionPane.PLAIN_MESSAGE);
             this.setVisible(true);
             }
             else
             {
              if(!jComboGender.getSelectedItem().equals("Select Gender"))
              {
                  DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
         String date1 = fmt.format(jDCDob.getDate());
         int birthyear = Integer.parseInt(date1.substring(0, 4));
         int birthmonth = Integer.parseInt(date1.substring(5, 7));
         int birthdate = Integer.parseInt(date1.substring(8, 10));
         
         LocalDate dateofbirth = LocalDate.of(birthyear,birthmonth, birthdate);
         LocalDate todayDate = LocalDate.now();
         
         Period diff = Period.between(dateofbirth, todayDate);
         String calculate = String.format("%02d", diff.getYears());
         int calculateAge = Integer.parseInt(calculate);
         
                if(calculateAge>=18)
                {
                  
           Name.add(jtxtName.getText());
           FName.add(jtxtFName.getText());
           Cnic.add(jtxtCnic.getText());
           Gender.add(jComboGender.getSelectedItem().toString());
           Dob.add(date1);
           Age.add(calculate);
           Address.add(jtxtAddress.getText());
           VoterId.add((Vid+i));
                  
            this.setVisible(false);    
            JOptionPane.showMessageDialog(null, "Voter has been added.\nVoter ID: "+VoterId.get(i)+"\nVoter Name: "+Name.get(i) , "Message", JOptionPane.PLAIN_MESSAGE);
    
            backAdmin.setVisible(true);
            i++;
                }
                
                else
                {
                    Toolkit.getDefaultToolkit().beep();
                 JOptionPane.showMessageDialog(null, "Entered age is not legal. Age should be 18 or above." , "Message", JOptionPane.PLAIN_MESSAGE);
                 this.setVisible(true);
                
                }
              }
              else
              {
              JOptionPane.showMessageDialog(null, "Select Gender." , "Message", JOptionPane.PLAIN_MESSAGE);
                 this.setVisible(true);
              }
                  
             }
         }
          }
         
         
       else
       {
           JOptionPane.showMessageDialog(null, "Fill all the fields" , "Message", JOptionPane.PLAIN_MESSAGE);
       this.setVisible(true);
       }
     
     
      
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jtxtFNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtxtFNameInputMethodTextChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jtxtFNameInputMethodTextChanged

    private void jtxtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNameKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c) || evt.getKeyCode()== KeyEvent.VK_SHIFT ){
            jtxtName.setEditable(true);
        }
        else{
            jtxtName.setEditable(false);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Only alphabets are allowed." , "Error", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jtxtNameKeyPressed

    private void jtxtFNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFNameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c) || evt.getKeyCode()== KeyEvent.VK_SHIFT){
            jtxtFName.setEditable(true);
        }
        else{
            jtxtFName.setEditable(false);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Only alphabets are allowed." , "Error", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jtxtFNameKeyPressed

    private void jtxtCnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCnicKeyPressed
        // TODO add your handling code here:
        int cniclength = jtxtCnic.getText().length();
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            jtxtCnic.setEditable(true);
        }
        else{
            Toolkit.getDefaultToolkit().beep();
            jtxtCnic.setEditable(false);
            JOptionPane.showMessageDialog(null, "Only integers are allowed." , "Error", JOptionPane.PLAIN_MESSAGE);
        }
        if(cniclength>12){
            if(Character.isISOControl(c))
            {
            jtxtCnic.setEditable(true);
            }
            else
            jtxtCnic.setEditable(false);
        }

    }//GEN-LAST:event_jtxtCnicKeyPressed

    private void jtxtCnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCnicActionPerformed

    private void jComboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboGenderActionPerformed

    private void jDCDobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDCDobFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jDCDobFocusLost

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void jDCDobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDCDobKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jDCDobKeyPressed

    private void jbtnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnAddKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
              if(!(jtxtName.getText().trim().equals("") || jtxtFName.getText().trim().equals("") || jtxtCnic.getText().trim().equals("") 
                 || jtxtAddress.getText().trim().equals("")))
         {
             if((jDCDob.getDate() == null)){
             JOptionPane.showMessageDialog(null, "Select Date of Birth." , "Error", JOptionPane.PLAIN_MESSAGE);
             this.setVisible(true);
             }
             else{
                int cniclength = jtxtCnic.getText().length(); 
             if(cniclength<=12)
             {
             JOptionPane.showMessageDialog(null, "Cnic should have 13 digits." , "Error", JOptionPane.PLAIN_MESSAGE);
             this.setVisible(true);
             }
             else
             {
              if(!jComboGender.getSelectedItem().equals("Select Gender"))
              {
                  DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
         String date1 = fmt.format(jDCDob.getDate());
         int birthyear = Integer.parseInt(date1.substring(0, 4));
         int birthmonth = Integer.parseInt(date1.substring(5, 7));
         int birthdate = Integer.parseInt(date1.substring(8, 10));
         
         LocalDate dateofbirth = LocalDate.of(birthyear,birthmonth, birthdate);
         LocalDate todayDate = LocalDate.now();
         
         Period diff = Period.between(dateofbirth, todayDate);
         String calculate = String.format("%02d", diff.getYears());
         int calculateAge = Integer.parseInt(calculate);
          
                if(calculateAge>=18)
                {
                  
           Name.add(jtxtName.getText());
           FName.add(jtxtFName.getText());
           Cnic.add(jtxtCnic.getText());
           Gender.add(jComboGender.getSelectedItem().toString());
           Dob.add(date1);
           Age.add(calculate);
           Address.add(jtxtAddress.getText());
           VoterId.add((Vid+i));
                  
            this.setVisible(false);    
            JOptionPane.showMessageDialog(null, "Voter has been added.\nVoter ID: "+VoterId.get(i)+"\nVoter Name: "+Name.get(i) , "Message", JOptionPane.PLAIN_MESSAGE);
    
            backAdmin.setVisible(true);
            i++;
                }
                
                else
                {
                    Toolkit.getDefaultToolkit().beep();
                 JOptionPane.showMessageDialog(null, "Entered age is not legal. Age should be 18 or above." , "Message", JOptionPane.PLAIN_MESSAGE);
                 this.setVisible(true);
                
                }
              }
              else
              {
              JOptionPane.showMessageDialog(null, "Select Gender." , "Message", JOptionPane.PLAIN_MESSAGE);
                 this.setVisible(true);
              }
                  
             }
         }
          }
         
         
       else
       {
           JOptionPane.showMessageDialog(null, "Fill all the fields" , "Message", JOptionPane.PLAIN_MESSAGE);
       this.setVisible(true);
       }
     
        }
    }//GEN-LAST:event_jbtnAddKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVoter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboGender;
    private com.toedter.calendar.JDateChooser jDCDob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCnic;
    private javax.swing.JTextField jtxtFName;
    private javax.swing.JTextField jtxtName;
    // End of variables declaration//GEN-END:variables
}
