/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.OnlineVotingSystem;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Election extends javax.swing.JFrame {
        static int countA=0;
        static int countB=0;
        static int countC=0;
        static int countD=0;
        MainMenu mainElect = new MainMenu();
        
    /**
     * Creates new form Election
     */
    public Election() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnPartyA = new javax.swing.JButton();
        jbtnPartyB = new javax.swing.JButton();
        jbtnPartyC = new javax.swing.JButton();
        jbtnPartyD = new javax.swing.JButton();
        jlblelEctionAlert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnPartyA.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnPartyA.setText("Party-A");
        jbtnPartyA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPartyAActionPerformed(evt);
            }
        });
        jbtnPartyA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnPartyAKeyPressed(evt);
            }
        });

        jbtnPartyB.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnPartyB.setText("Party-B");
        jbtnPartyB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPartyBActionPerformed(evt);
            }
        });
        jbtnPartyB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnPartyBKeyPressed(evt);
            }
        });

        jbtnPartyC.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnPartyC.setText("Party-C");
        jbtnPartyC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPartyCActionPerformed(evt);
            }
        });
        jbtnPartyC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnPartyCKeyPressed(evt);
            }
        });

        jbtnPartyD.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnPartyD.setText("Party-D");
        jbtnPartyD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPartyDActionPerformed(evt);
            }
        });
        jbtnPartyD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnPartyDKeyPressed(evt);
            }
        });

        jlblelEctionAlert.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblelEctionAlert.setForeground(new java.awt.Color(255, 0, 0));
        jlblelEctionAlert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblelEctionAlert.setText("* Vote only for one.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblelEctionAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPartyD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPartyB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPartyA, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jbtnPartyC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnPartyA, jbtnPartyB, jbtnPartyC, jbtnPartyD});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jlblelEctionAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbtnPartyA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jbtnPartyB)
                .addGap(33, 33, 33)
                .addComponent(jbtnPartyC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbtnPartyD)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnPartyA, jbtnPartyB, jbtnPartyC, jbtnPartyD});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPartyBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPartyBActionPerformed
        // TODO add your handling code here:
        countB++;
        JOptionPane.showMessageDialog(null, "Your Vote has been added." , "Message", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
        mainElect.setVisible(true);
    }//GEN-LAST:event_jbtnPartyBActionPerformed

    private void jbtnPartyCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPartyCActionPerformed
        // TODO add your handling code here:
        countC++;
        JOptionPane.showMessageDialog(null, "Your Vote has been added." , "Message", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
        mainElect.setVisible(true);
    }//GEN-LAST:event_jbtnPartyCActionPerformed

    private void jbtnPartyAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPartyAActionPerformed
        // TODO add your handling code here:
        countA++;
        JOptionPane.showMessageDialog(null, "Your Vote has been added." , "Message", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
        mainElect.setVisible(true);
    }//GEN-LAST:event_jbtnPartyAActionPerformed

    private void jbtnPartyDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPartyDActionPerformed
        // TODO add your handling code here:
        countD++;
        JOptionPane.showMessageDialog(null, "Your Vote has been added." , "Message", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
        mainElect.setVisible(true);
    }//GEN-LAST:event_jbtnPartyDActionPerformed

    private void jbtnPartyAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnPartyAKeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            countA++;
        JOptionPane.showMessageDialog(null, "Your Vote has been added." , "Message", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
        mainElect.setVisible(true);
        }
    }//GEN-LAST:event_jbtnPartyAKeyPressed

    private void jbtnPartyBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnPartyBKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
            countB++;
        JOptionPane.showMessageDialog(null, "Your Vote has been added." , "Message", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
        mainElect.setVisible(true);
        }
    }//GEN-LAST:event_jbtnPartyBKeyPressed

    private void jbtnPartyCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnPartyCKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
            countC++;
        JOptionPane.showMessageDialog(null, "Your Vote has been added." , "Message", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
        mainElect.setVisible(true);
        }
    }//GEN-LAST:event_jbtnPartyCKeyPressed

    private void jbtnPartyDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnPartyDKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
            countD++;
        JOptionPane.showMessageDialog(null, "Your Vote has been added." , "Message", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
        mainElect.setVisible(true);
        }
    }//GEN-LAST:event_jbtnPartyDKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Election.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Election.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Election.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Election.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Election().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnPartyA;
    private javax.swing.JButton jbtnPartyB;
    private javax.swing.JButton jbtnPartyC;
    private javax.swing.JButton jbtnPartyD;
    private javax.swing.JLabel jlblelEctionAlert;
    // End of variables declaration//GEN-END:variables
}
