/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.OnlineVotingSystem;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class UpdateVoter extends javax.swing.JFrame {
    static int checkUpdate;
    MainMenu backmain = new MainMenu();
    
    /**
     * Creates new form UpdateVoter
     */
    public UpdateVoter() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtUpdateID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbtnUpdate = new javax.swing.JButton();
        jlblOldName = new javax.swing.JLabel();
        jtxtNewName = new javax.swing.JTextField();
        jlblOldFName = new javax.swing.JLabel();
        jlblOldCnic = new javax.swing.JLabel();
        jlblOldGender = new javax.swing.JLabel();
        jlblOldDob = new javax.swing.JLabel();
        jlblOldAge = new javax.swing.JLabel();
        jlblOldAddress = new javax.swing.JLabel();
        jtxtNewFName = new javax.swing.JTextField();
        jtxtNewCnic = new javax.swing.JTextField();
        jtxtNewAddress = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboNewGender = new javax.swing.JComboBox<>();
        jDCNewDob = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Voter ID");

        jtxtUpdateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUpdateIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("     Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("     Father Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("     Cnic:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("     Gender:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("     Date Of Birth:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("     Age:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("     Address:");

        jbtnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jbtnUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnUpdateKeyPressed(evt);
            }
        });

        jlblOldName.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jlblOldName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jtxtNewName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNewNameActionPerformed(evt);
            }
        });
        jtxtNewName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNewNameKeyPressed(evt);
            }
        });

        jlblOldFName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlblOldFName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jlblOldCnic.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlblOldCnic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jlblOldGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlblOldGender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jlblOldDob.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlblOldDob.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jlblOldAge.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlblOldAge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jlblOldAddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlblOldAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jtxtNewFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNewFNameKeyPressed(evt);
            }
        });

        jtxtNewCnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNewCnicKeyPressed(evt);
            }
        });

        jbtnSearch.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtnSearch.setText("Search");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });
        jbtnSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnSearchKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("* without dashes (xxxxxxxxxxxxx)");

        jComboNewGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Other" }));

        jDCNewDob.setDateFormatString("yyyy-MM-dd");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Back to Main");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblOldName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblOldFName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblOldCnic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblOldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblOldDob, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblOldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblOldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDCNewDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboNewGender, 0, 137, Short.MAX_VALUE)
                            .addComponent(jtxtNewAddress)
                            .addComponent(jtxtNewCnic)
                            .addComponent(jtxtNewFName)
                            .addComponent(jtxtNewName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jtxtUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnSearch)))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jbtnUpdate});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblOldName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlblOldFName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNewFName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlblOldCnic, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNewCnic, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jlblOldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboNewGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jlblOldDob, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDCNewDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlblOldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jlblOldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNewAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboNewGender, jDCNewDob, jtxtNewCnic});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jbtnUpdate});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtUpdateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUpdateIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUpdateIDActionPerformed

    private void jtxtNewNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNewNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNewNameActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        // TODO add your handling code here:
         if(jtxtUpdateID.getText().trim().equals("")){
       JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(true);
       }
         else{
             try{
                  checkUpdate = AddVoter.VoterId.indexOf(jtxtUpdateID.getText());
                   if(AddVoter.VoterId.get(checkUpdate).equals(jtxtUpdateID.getText()))
                  {
            jlblOldName.setText(AddVoter.Name.get(checkUpdate).toUpperCase());
            jlblOldFName.setText(AddVoter.FName.get(checkUpdate).toUpperCase());
            jlblOldCnic.setText(AddVoter.Cnic.get(checkUpdate));
            jlblOldGender.setText(AddVoter.Gender.get(checkUpdate).toUpperCase());
            jlblOldDob.setText(AddVoter.Dob.get(checkUpdate));
            jlblOldAge.setText(AddVoter.Age.get(checkUpdate));
            jlblOldAddress.setText(AddVoter.Address.get(checkUpdate));
            
        } // end of if
             }
             catch(IndexOutOfBoundsException e){
             JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(true);
             }
       
       
         } // end of outer else
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
        try{
         if(jtxtUpdateID.getText().trim().equals("")){
       JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                jtxtNewName.setText(null);      jtxtNewFName.setText(null);     jtxtNewCnic.setText(null); 
                jComboNewGender.setSelectedIndex(0);     jDCNewDob.setDate(null);    jtxtNewAddress.setText(null);
                this.setVisible(true);
       }
         else{
        if(!(jtxtNewName.getText().trim().equals("") || jtxtNewFName.getText().trim().equals("") || jtxtNewCnic.getText().trim().equals("") 
               || jtxtNewAddress.getText().trim().equals("")))
        {
            if((jDCNewDob.getDate() == null)){
             JOptionPane.showMessageDialog(null, "Select Date of Birth." , "Error", JOptionPane.PLAIN_MESSAGE);
             this.setVisible(true);
             }
            else{
             int cniclength = jtxtNewCnic.getText().length(); 
             if(cniclength<=12)
             {
             JOptionPane.showMessageDialog(null, "Cnic should have 13 digits." , "Error", JOptionPane.PLAIN_MESSAGE);
             this.setVisible(true);
             }
             else{
                 if(!jComboNewGender.getSelectedItem().equals("Select Gender"))
                 {
                           DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
         String date1 = fmt.format(jDCNewDob.getDate());
         int birthyear = Integer.parseInt(date1.substring(0, 4));
         int birthmonth = Integer.parseInt(date1.substring(5, 7));
         int birthdate = Integer.parseInt(date1.substring(8, 10));
         
         LocalDate dateofbirth = LocalDate.of(birthyear,birthmonth, birthdate);
         LocalDate todayDate = LocalDate.now();
         
         Period diff = Period.between(dateofbirth, todayDate);
         String calculate = String.format("%02d", diff.getYears());
         int calculateNewAge = Integer.parseInt(calculate);
             if(calculateNewAge>=18)
             {
                
                AddVoter.Name.set(checkUpdate, jtxtNewName.getText());
                AddVoter.FName.set(checkUpdate, jtxtNewFName.getText());
                AddVoter.Cnic.set(checkUpdate, jtxtNewCnic.getText());
                AddVoter.Gender.set(checkUpdate, jComboNewGender.getSelectedItem().toString());
                AddVoter.Dob.set(checkUpdate, date1);
                AddVoter.Age.set(checkUpdate, calculate);
                AddVoter.Address.set(checkUpdate, jtxtNewAddress.getText());
                JOptionPane.showMessageDialog(null, "Voter has been Updated." , "Message", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(false);
                backmain.setVisible(true);
             }
             else
             {
                 JOptionPane.showMessageDialog(null, "Entered age is not legal. Age should be 18 or above." , "Message", JOptionPane.PLAIN_MESSAGE);
                 this.setVisible(true);
                 
            }
                 }
                 else
                     {
              JOptionPane.showMessageDialog(null, "Select Gender." , "Message", JOptionPane.PLAIN_MESSAGE);
                 this.setVisible(true);
              }
             }
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Fill all the fields" , "Message", JOptionPane.PLAIN_MESSAGE);
            this.setVisible(true);
       }
    }
    }
        catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "You changed Voter Id." , "Error", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(true);
        
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jtxtNewCnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNewCnicKeyPressed
        // TODO add your handling code here:
         int cniclength = jtxtNewCnic.getText().length();
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            jtxtNewCnic.setEditable(true);
        }
        else{
            Toolkit.getDefaultToolkit().beep();
            jtxtNewCnic.setEditable(false);
            JOptionPane.showMessageDialog(null, "Only integers are allowed." , "Error", JOptionPane.PLAIN_MESSAGE);
        }
         if(cniclength>12){
            if(Character.isISOControl(c))
        jtxtNewCnic.setEditable(true);
            else
                jtxtNewCnic.setEditable(false);
        }
    }//GEN-LAST:event_jtxtNewCnicKeyPressed

    private void jtxtNewNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNewNameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c) || evt.getKeyCode()== KeyEvent.VK_SHIFT){
            jtxtNewName.setEditable(true);
        }
        else{
            Toolkit.getDefaultToolkit().beep();
            jtxtNewName.setEditable(false);
            JOptionPane.showMessageDialog(null, "Only alphabets are allowed." , "Error", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jtxtNewNameKeyPressed

    private void jtxtNewFNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNewFNameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c) || evt.getKeyCode()== KeyEvent.VK_SHIFT){
            jtxtNewFName.setEditable(true);
        }
        else{
            Toolkit.getDefaultToolkit().beep();
            jtxtNewFName.setEditable(false);
            JOptionPane.showMessageDialog(null, "Only alphabets are allowed." , "Error", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jtxtNewFNameKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        backmain.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnSearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
         if(jtxtUpdateID.getText().trim().equals("")){
       JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(true);
       }
         else{
             try{
                  checkUpdate = AddVoter.VoterId.indexOf(jtxtUpdateID.getText());
                   if(AddVoter.VoterId.get(checkUpdate).equals(jtxtUpdateID.getText()))
                  {
            jlblOldName.setText(AddVoter.Name.get(checkUpdate).toUpperCase());
            jlblOldFName.setText(AddVoter.FName.get(checkUpdate).toUpperCase());
            jlblOldCnic.setText(AddVoter.Cnic.get(checkUpdate));
            jlblOldGender.setText(AddVoter.Gender.get(checkUpdate).toUpperCase());
            jlblOldDob.setText(AddVoter.Dob.get(checkUpdate));
            jlblOldAge.setText(AddVoter.Age.get(checkUpdate));
            jlblOldAddress.setText(AddVoter.Address.get(checkUpdate));
            
        } // end of if
             }
             catch(IndexOutOfBoundsException e){
             JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(true);
             }
       
       
         } // end of outer else
        }
    }//GEN-LAST:event_jbtnSearchKeyPressed

    private void jbtnUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnUpdateKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
         if(jtxtUpdateID.getText().trim().equals("")){
       JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                jtxtNewName.setText(null);      jtxtNewFName.setText(null);     jtxtNewCnic.setText(null); 
                jComboNewGender.setSelectedIndex(0);     jDCNewDob.setDate(null);    jtxtNewAddress.setText(null);
                this.setVisible(true);
       }
         else{
        if(!(jtxtNewName.getText().trim().equals("") || jtxtNewFName.getText().trim().equals("") || jtxtNewCnic.getText().trim().equals("") 
               || jtxtNewAddress.getText().trim().equals("")))
        {
            if((jDCNewDob.getDate() == null)){
             JOptionPane.showMessageDialog(null, "Select Date of Birth." , "Error", JOptionPane.PLAIN_MESSAGE);
             this.setVisible(true);
             }
            else{
             int cniclength = jtxtNewCnic.getText().length(); 
             if(cniclength<=12)
             {
             JOptionPane.showMessageDialog(null, "Cnic should have 13 digits." , "Error", JOptionPane.PLAIN_MESSAGE);
             this.setVisible(true);
             }
             else{
                 if(!jComboNewGender.getSelectedItem().equals("Select Gender"))
                 {
                           DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
         String date1 = fmt.format(jDCNewDob.getDate());
         int birthyear = Integer.parseInt(date1.substring(0, 4));
         int birthmonth = Integer.parseInt(date1.substring(5, 7));
         int birthdate = Integer.parseInt(date1.substring(8, 10));
         
         LocalDate dateofbirth = LocalDate.of(birthyear,birthmonth, birthdate);
         LocalDate todayDate = LocalDate.now();
         
         Period diff = Period.between(dateofbirth, todayDate);
         String calculate = String.format("%02d", diff.getYears());
         int calculateNewAge = Integer.parseInt(calculate);
             if(calculateNewAge>=18)
             {
                
                AddVoter.Name.set(checkUpdate, jtxtNewName.getText());
                AddVoter.FName.set(checkUpdate, jtxtNewFName.getText());
                AddVoter.Cnic.set(checkUpdate, jtxtNewCnic.getText());
                AddVoter.Gender.set(checkUpdate, jComboNewGender.getSelectedItem().toString());
                AddVoter.Dob.set(checkUpdate, date1);
                AddVoter.Age.set(checkUpdate, calculate);
                AddVoter.Address.set(checkUpdate, jtxtNewAddress.getText());
                JOptionPane.showMessageDialog(null, "Voter has been Updated." , "Message", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(false);
                backmain.setVisible(true);
             }
             else
             {
                 JOptionPane.showMessageDialog(null, "Entered age is not legal. Age should be 18 or above." , "Message", JOptionPane.PLAIN_MESSAGE);
                 this.setVisible(true);
                 
            }
                 }
                 else
                     {
              JOptionPane.showMessageDialog(null, "Select Gender." , "Message", JOptionPane.PLAIN_MESSAGE);
                 this.setVisible(true);
              }
             }
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Fill all the fields" , "Message", JOptionPane.PLAIN_MESSAGE);
            this.setVisible(true);
       }
    }
        }
    }//GEN-LAST:event_jbtnUpdateKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        this.setVisible(false);
        backmain.setVisible(true);
        }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateVoter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboNewGender;
    private com.toedter.calendar.JDateChooser jDCNewDob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JLabel jlblOldAddress;
    private javax.swing.JLabel jlblOldAge;
    private javax.swing.JLabel jlblOldCnic;
    private javax.swing.JLabel jlblOldDob;
    private javax.swing.JLabel jlblOldFName;
    private javax.swing.JLabel jlblOldGender;
    private javax.swing.JLabel jlblOldName;
    private javax.swing.JTextField jtxtNewAddress;
    private javax.swing.JTextField jtxtNewCnic;
    private javax.swing.JTextField jtxtNewFName;
    private javax.swing.JTextField jtxtNewName;
    private javax.swing.JTextField jtxtUpdateID;
    // End of variables declaration//GEN-END:variables
}
