/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.OnlineVotingSystem;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class VoterId extends javax.swing.JFrame {
        Election elect = new Election();
        MainMenu mb = new MainMenu();
        public static ArrayList<Integer> count = new ArrayList<Integer>(20);
        
    /**
     * Creates new form VoterId
     */
    public VoterId() {
        initComponents();
        this.setResizable(false);
    }
    public void count(){
            for(int i=0;i<20;i++){
            count.add(0);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtID = new javax.swing.JTextField();
        jtxtIDName = new javax.swing.JTextField();
        jbtnEnterVoter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnBackMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIDActionPerformed(evt);
            }
        });

        jbtnEnterVoter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnEnterVoter.setText("Enter");
        jbtnEnterVoter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnEnterVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnterVoterActionPerformed(evt);
            }
        });
        jbtnEnterVoter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnEnterVoterKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Voter ID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        jbtnBackMain.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnBackMain.setText("Main Menu");
        jbtnBackMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnBackMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackMainActionPerformed(evt);
            }
        });
        jbtnBackMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnBackMainKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtIDName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbtnBackMain)
                        .addGap(93, 93, 93)
                        .addComponent(jbtnEnterVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtID, jtxtIDName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnBackMain, jbtnEnterVoter});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jtxtIDName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEnterVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBackMain))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxtID, jtxtIDName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnBackMain, jbtnEnterVoter});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIDActionPerformed

    private void jbtnEnterVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnterVoterActionPerformed
        // TODO add your handling code here:
        
        this.count();
       if(jtxtID.getText().trim().equals("")){
       JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(true);
       }
       else
       {
           try{
        int checkindex = AddVoter.VoterId.indexOf(jtxtID.getText());
        if(!(count.get(checkindex)>0))
        {
            
            if(AddVoter.VoterId.get(checkindex).equals(jtxtID.getText()))
            {
                if(AddVoter.Name.get(checkindex).equals(jtxtIDName.getText()))
                    {
                         count.set(checkindex, 1);
                        this.setVisible(false);
                        elect.setVisible(true);
                    }
                else
                    {
                        JOptionPane.showMessageDialog(null, "Voter Name is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                        this.setVisible(true);
                    }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(true);
            }
            
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Voter can cast only one vote." , "Error", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
        mb.setVisible(true);
        }
           }
           catch(IndexOutOfBoundsException e){
             JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(true);
             }
       }
       
       
    }//GEN-LAST:event_jbtnEnterVoterActionPerformed

    private void jbtnEnterVoterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnEnterVoterKeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
               
        this.count();
       if(jtxtID.getText().trim().equals("")){
       JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(true);
       }
       else
       {
           try{
        int checkindex = AddVoter.VoterId.indexOf(jtxtID.getText());
        if(!(count.get(checkindex)>0))
        {
            
            if(AddVoter.VoterId.get(checkindex).equals(jtxtID.getText()))
            {
                if(AddVoter.Name.get(checkindex).equals(jtxtIDName.getText()))
                    {
                         count.set(checkindex, 1);
                        this.setVisible(false);
                        elect.setVisible(true);
                    }
                else
                    {
                        JOptionPane.showMessageDialog(null, "Voter Name is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                        this.setVisible(true);
                    }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(true);
            }
            
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Voter can cast only one vote." , "Error", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
        mb.setVisible(true);
        }
           }
           catch(IndexOutOfBoundsException e){
             JOptionPane.showMessageDialog(null, "Voter ID is not Valid." , "Error", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(true);
             }
       }
       
        }
    }//GEN-LAST:event_jbtnEnterVoterKeyPressed

    private void jbtnBackMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackMainActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mb.setVisible(true);
    }//GEN-LAST:event_jbtnBackMainActionPerformed

    private void jbtnBackMainKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnBackMainKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
           this.setVisible(false);
        mb.setVisible(true);
        }
    }//GEN-LAST:event_jbtnBackMainKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoterId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoterId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoterId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoterId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoterId().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnBackMain;
    private javax.swing.JButton jbtnEnterVoter;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtIDName;
    // End of variables declaration//GEN-END:variables
}
